### ISSUE TITLE
bleak_agent_transform.js missing.

### ISSUE THREAD

**Issue by rhalff** [plasma-umass/BLeak#1]
Hi, I am trying get this running, however there seems to be a missing `bleak_agent_transform.js` file.

```yaml
$ node build/src/frontends/bleak.js --config config.js --out ./out
MITMProxy not running; starting up mitmproxy.
Loading script: /home/rhalff/git/rhalff/BLeak/node_modules/mitmproxy/scripts/proxy.py
Proxy server listening at http://0.0.0.0:8080
127.0.0.1:40574: clientconnect
127.0.0.1:40576: clientconnect
127.0.0.1:40574: clientdisconnect
127.0.0.1:40576: clientdisconnect
127.0.0.1:40582: clientconnect
{ Error: ENOENT: no such file or directory, open '/home/rhalff/git/rhalff/BLeak/build/src/lib/bleak_agent_transform.js'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Object.getInterceptor (/home/rhalff/git/rhalff/BLeak/build/src/lib/mitmproxy_interceptor.js:37:37)
    at Object.configureProxy (/home/rhalff/git/rhalff/BLeak/build/src/common/util.js:10:40)
    at BLeakDetector.configureProxy (/home/rhalff/git/rhalff/BLeak/build/src/lib/bleak.js:92:23)
    at new BLeakDetector (/home/rhalff/git/rhalff/BLeak/build/src/lib/bleak.js:61:14)
    at Function.<anonymous> (/home/rhalff/git/rhalff/BLeak/build/src/lib/bleak.js:71:30)
    at Generator.next (<anonymous>)
    at /home/rhalff/git/rhalff/BLeak/build/src/lib/bleak.js:7:71
    at new Promise (<anonymous>)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/rhalff/git/rhalff/BLeak/build/src/lib/bleak_agent_transform.js' }
```

**Comment by jvilk** [comment]
Sorry about that; I just added the missing file, and verified that BLeak starts up fine now.

I also fixed some Git LFS issues that were caused during a migration from Bitbucket.

**Comment by rhalff** [comment]
Thanks a lot, much appreciated!
