### ISSUE TITLE
BLeak error when running on https://in.bookmyshow.com

### ISSUE THREAD

**Issue by mjayprateek** [plasma-umass/BLeak#32]
I encountered the following error while running BLeak on above mentioned website.

BLeak config file is attached: [bleak_bms.js.txt](https://github.com/plasma-umass/BLeak/files/2320845/bleak_bms.js.txt)

```
bleak run  --snapshot --config bleak_bms.js --out ./bms

DevTools listening on ws://127.0.0.1:52111/devtools/browser/e1a850ae-054d-485a-9834-6a946da45098
2018-08-25 18:16:07.622 Google Chrome[31035:851482] *** Owner supplied to -[NSTrackingArea initWithRect:options:owner:userInfo:] referenced a deallocating object. Tracking area behavior is undefined. Break on NSTrackingAreaDeallocatingOwnerError to debug.
[                    ] 0% [1/276] 0.0s (ETA 0.0s) Navigating to https://in.bookmyshow.com/movies2018-08-25 18:16:08.040 Google Chrome[31035:851482] Errors logged by ksadmin: KSKeyedPersistentStore store directory does not exist. [com.google.UpdateEngine.CommonErrorDomain:501 - '/Library/Google/GoogleSoftwareUpdate/TicketStore' - 'KSKeyedPersistentStore.m:327']
KSPersistentTicketStore failed to load tickets. (productID: com.google.Chrome) [com.google.UpdateEngine.CoreErrorDomain:1051 - '/Library/Google/GoogleSoftwareUpdate/TicketStore/Keystone.ticketstore'] (KSKeyedPersistentStore store directory does not exist. - '/Library/Google/GoogleSoftwareUpdate/TicketStore' [com.google.UpdateEngine.CommonErrorDomain:501])
ksadmin cannot access the ticket store:<KSUpdateError:0x7f995f407a10
	domain="com.google.UpdateEngine.CoreErrorDomain"
	code=1051
	userInfo={
		function = "-[KSProductKeyedStore(ProtectedMethods) errorForStoreError:productID:message:timeoutMessage:]";
		date = 2018-08-25 12:46:08 +0000;
		productids = {(
			"com.google.Chrome"
		)};
		filename = "KSProductKeyedStore.m";
		line = 102;
		NSFilePath = "/Library/Google/GoogleSoftwareUpdate/TicketStore/Keystone.ticketstore";
		NSUnderlyingError = <KSError:0x7f995f404c00
			domain="com.google.UpdateEngine.CommonErrorDomain"
			code=501
			userInfo={
				NSLocalizedDescription = "KSKeyedPersistentStore store directory does not exist.";
				line = 327;
				filename = "KSKeyedPersistentStore.m";
				function = "-[KSKeyedPersistentStore(PrivateMethods) validateStorePath]";
				NSFilePath = "/Library/Google/GoogleSoftwareUpdate/TicketStore";
				date = 2018-08-25 12:46:08 +0000;
			}
		>;
		NSLocalizedDescription = "KSPersistentTicketStore failed to load tickets.";
	}
>
https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:62:158 Uncaught ReferenceError: loadCarousel is not defined
    at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:63:159
undefined
  https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:62:158

https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:2074:233 Uncaught ReferenceError: googletag is not defined
    at Object.global.initCarousels (https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:2075:234)
    at Object.process (https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:625:88)
    at success (https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:613:16)
    at Object.success (https://in.bmscdn.com/static/js/misc-19fdffad73.js:2993:14)
    at j (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:876:108)
    at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:919:98)
    at x (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2333:575)
    at XMLHttpRequest.<anonymous> (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2457:138)
undefined
  global.initCarousels at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:2074:233
  process at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:624:87
  success at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:612:15
  success at https://in.bmscdn.com/static/js/misc-19fdffad73.js:2992:13
  j at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:875:107
  fireWith at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:918:97
  x at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2332:574
  https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2456:137

https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:2074:233 Uncaught ReferenceError: googletag is not defined
    at Object.global.initCarousels (https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:2075:234)
    at Object.process (https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:625:88)
    at success (https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:613:16)
    at Object.success (https://in.bmscdn.com/static/js/misc-19fdffad73.js:2993:14)
    at j (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:876:108)
    at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:919:98)
    at x (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2333:575)
    at XMLHttpRequest.<anonymous> (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2457:138)
undefined
  global.initCarousels at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:2074:233
  process at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:624:87
  success at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:612:15
  success at https://in.bmscdn.com/static/js/misc-19fdffad73.js:2992:13
  j at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:875:107
  fireWith at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:918:97
  x at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2332:574
  https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2456:137

https://www.googletagmanager.com/gtm.js?id=GTM-MH7KN6:7324:8 Uncaught Object
undefined
  error at https://www.googletagmanager.com/gtm.js?id=GTM-MH7KN6:7324:8
  t.Ha.onerror at https://www.googletagmanager.com/gtm.js?id=GTM-MH7KN6:7540:14

[                    ] 0% [1/276] 0.0s (ETA 0.0s) Navigating to https://in.bookmyshow.com/movies[31042:35627:0825/181614.986003:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:62:158 Uncaught ReferenceError: loadCarousel is not defined
    at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:63:159
undefined
  https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:62:158

https://www.googletagmanager.com/gtm.js?id=GTM-MH7KN6:7324:8 Uncaught Object
undefined
  error at https://www.googletagmanager.com/gtm.js?id=GTM-MH7KN6:7324:8
  t.Ha.onerror at https://www.googletagmanager.com/gtm.js?id=GTM-MH7KN6:7540:14

https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:2074:233 Uncaught ReferenceError: googletag is not defined
    at Object.global.initCarousels (https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:2075:234)
    at Object.process (https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:625:88)
    at success (https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:613:16)
    at Object.success (https://in.bmscdn.com/static/js/misc-19fdffad73.js:2993:14)
    at j (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:876:108)
    at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:919:98)
    at x (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2333:575)
    at XMLHttpRequest.<anonymous> (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2457:138)
undefined
  global.initCarousels at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:2074:233
  process at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:624:87
  success at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:612:15
  success at https://in.bmscdn.com/static/js/misc-19fdffad73.js:2992:13
  j at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:875:107
  fireWith at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:918:97
  x at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2332:574
  https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2456:137

https://www.googletagmanager.com/gtm.js?id=GTM-MH7KN6:7324:8 Uncaught Object
undefined
  error at https://www.googletagmanager.com/gtm.js?id=GTM-MH7KN6:7324:8
  t.Ha.onerror at https://www.googletagmanager.com/gtm.js?id=GTM-MH7KN6:7540:14

https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:2074:233 Uncaught ReferenceError: googletag is not defined
    at Object.global.initCarousels (https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:2075:234)
    at Object.process (https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:625:88)
    at success (https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:613:16)
    at Object.success (https://in.bmscdn.com/static/js/misc-19fdffad73.js:2993:14)
    at j (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:876:108)
    at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:919:98)
    at x (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2333:575)
    at XMLHttpRequest.<anonymous> (https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2457:138)
undefined
  global.initCarousels at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:2074:233
  process at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:624:87
  success at https://in.bmscdn.com/static/js/movielisting_v1-cc263e01bf.js:612:15
  success at https://in.bmscdn.com/static/js/misc-19fdffad73.js:2992:13
  j at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:875:107
  fireWith at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:918:97
  x at https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2332:574
  https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js:2456:137

https://www.googletagmanager.com/gtm.js?id=GTM-MH7KN6:7324:8 Uncaught Object
undefined
  error at https://www.googletagmanager.com/gtm.js?id=GTM-MH7KN6:7324:8
  t.Ha.onerror at https://www.googletagmanager.com/gtm.js?id=GTM-MH7KN6:7540:14

[=                   ] 7% [18/276] 51.2s (ETA 733.8s) Waiting 3000 ms before proceedingWeird! Found JS node with the following children: []
(node:31024) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at inlineScripts.forEach (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/transformations.js:105:85)
    at Array.forEach (<anonymous>)
    at Object.injectIntoHead (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/transformations.js:101:19)
    at log.timeEvent (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/mitmproxy_interceptor.js:121:69)
    at ProgressProgressBar.timeEvent (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/progress_progress_bar.js:81:20)
    at interceptor (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/mitmproxy_interceptor.js:120:21)
    at log.timeEvent (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/mitmproxy_interceptor.js:147:13)
    at ProgressProgressBar.timeEvent (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/progress_progress_bar.js:81:20)
    at MITMProxy.cb (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/mitmproxy_interceptor.js:146:13)
    at MITMProxy.<anonymous> (/usr/local/lib/node_modules/bleak-detector/node_modules/mitmproxy/dist/index.js:393:33)
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at inlineScripts.forEach (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/transformations.js:105:85)
    at Array.forEach (<anonymous>)
    at Object.injectIntoHead (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/transformations.js:101:19)
    at log.timeEvent (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/mitmproxy_interceptor.js:121:69)
    at ProgressProgressBar.timeEvent (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/progress_progress_bar.js:81:20)
    at interceptor (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/mitmproxy_interceptor.js:120:21)
    at log.timeEvent (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/mitmproxy_interceptor.js:147:13)
    at ProgressProgressBar.timeEvent (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/progress_progress_bar.js:81:20)
    at MITMProxy.cb (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/mitmproxy_interceptor.js:146:13)
    at MITMProxy.<anonymous> (/usr/local/lib/node_modules/bleak-detector/node_modules/mitmproxy/dist/index.js:393:33)
    at emitWarning (internal/process/promises.js:65:17)
    at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
    at runMicrotasksCallback (internal/process/next_tick.js:124:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[=                   ] 7% [18/276] 51.2s (ETA 733.8s) Waiting 3000 ms before proceeding(node:31024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
TypeError: Cannot read property 'data' of undefined
    at inlineScripts.forEach (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/transformations.js:105:85)
    at Array.forEach (<anonymous>)
    at Object.injectIntoHead (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/transformations.js:101:19)
    at log.timeEvent (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/mitmproxy_interceptor.js:121:69)
    at ProgressProgressBar.timeEvent (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/progress_progress_bar.js:81:20)
    at interceptor (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/mitmproxy_interceptor.js:120:21)
    at log.timeEvent (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/mitmproxy_interceptor.js:147:13)
    at ProgressProgressBar.timeEvent (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/progress_progress_bar.js:81:20)
    at MITMProxy.cb (/usr/local/lib/node_modules/bleak-detector/dist/node/lib/mitmproxy_interceptor.js:146:13)
    at MITMProxy.<anonymous> (/usr/local/lib/node_modules/bleak-detector/node_modules/mitmproxy/dist/index.js:393:33)
[=                   ] 7% [18/276] 51.2s (ETA 733.8s) Waiting 3000 ms before proceeding(node:31024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:92:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
    at runMicrotasksCallback (internal/process/next_tick.js:124:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
undefined:60:50 Uncaught TypeError: Cannot read property 'click' of undefined
    at Object.next (https://in.bookmyshow.com/movies:61:51)
    at <anonymous>:1:21
undefined
  next at https://in.bookmyshow.com/movies:60:50

[==                  ] 8% [22/276] 155.8s (ETA 1798.3s) Advancing to next state loop[2].next()
``` #31

**Comment by jvilk** [comment]
BookMyShow is not a single page web application. Each of those transitions completely reloads the page, which completely throws away the JavaScript heap and starts anew. Thus, BLeak is not applicable to the configuration file you have written.

The error you are seeing, though, I just fixed.
