### ISSUE TITLE
Run bleak,get error

### ISSUE THREAD

**Issue by hcg2008** [plasma-umass/BLeak#33]
MacOs High Sierra 10.13.6

a very simaple config for testing:
exports.url = "http://192.168.0.83/";
exports.loop = [
  // First state
  {
    // Return 'true' if the web application is ready for `next` to be run.
    check: function() {
			return !!document.getElementsByTagName('BUTTON');
    },
    // Transitions to the next state.
    next: function() {
			document.getElementsByTagName('BUTTON')[0].click();
    }
  },
  // Second (and last) state
  {
    check: function() {
      // Example: Make sure the body of the thread has loaded.
      return !!document.getElementById('thread-body');
    },
    // Since this is the last state in the loop, it must transition back to the first state.
    next: function() {
      // Example: Click back to group listing
      document.getElementById('group-001').click();
    }
  }
];

./bleak run --config ../bleak_config.js --out ../output/

DevTools listening on ws://127.0.0.1:63740/devtools/browser/fbfe026b-7624-4d4a-a809-98bbf9c8f87d
2018-09-04 14:16:21.115 Google Chrome[19904:5241419] *** Owner supplied to -[NSTrackingArea initWithRect:options:owner:userInfo:] referenced a deallocating object. Tracking area behavior is undefined. Break on NSTrackingAreaDeallocatingOwnerError to debug.
[                    ] 1% [1/136] 0.0s (ETA 0.0s) Navigating to http://192.168.0.83/(node:19894) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:159:11)
    at new Buffer (buffer.js:174:3)
    at embedSourceMap (/Users/hecaiguang/Desktop/MyProjects/nodeJS/bleak/BLeak-master/dist/node/lib/closure_state_transform.js:1955:74)
    at tryJSTransform (/Users/hecaiguang/Desktop/MyProjects/nodeJS/bleak/BLeak-master/dist/node/lib/closure_state_transform.js:1989:16)
    at Object.ensureES5 (/Users/hecaiguang/Desktop/MyProjects/nodeJS/bleak/BLeak-master/dist/node/lib/closure_state_transform.js:2039:12)
    at log.timeEvent (/Users/hecaiguang/Desktop/MyProjects/nodeJS/bleak/BLeak-master/dist/node/lib/mitmproxy_interceptor.js:138:77)
    at ProgressProgressBar.timeEvent (/Users/hecaiguang/Desktop/MyProjects/nodeJS/bleak/BLeak-master/dist/node/lib/progress_progress_bar.js:81:20)
    at interceptor (/Users/hecaiguang/Desktop/MyProjects/nodeJS/bleak/BLeak-master/dist/node/lib/mitmproxy_interceptor.js:137:29)
    at log.timeEvent (/Users/hecaiguang/Desktop/MyProjects/nodeJS/bleak/BLeak-master/dist/node/lib/mitmproxy_interceptor.js:147:13)
    at ProgressProgressBar.timeEvent (/Users/hecaiguang/Desktop/MyProjects/nodeJS/bleak/BLeak-master/dist/node/lib/progress_progress_bar.js:81:20)
http://192.168.0.83/static/js/vendor.0d7983918b9901905427.js:74178:58 Uncaught Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (http://192.168.0.83/static/js/vendor.0d7983918b9901905427.js:74179:59)
    at Object.<anonymous> (http://192.168.0.83/static/js/vendor.0d7983918b9901905427.js:74185:6)
    at n (http://192.168.0.83/static/js/manifest.bba22ef4cc111880865d.js:9:18)
    at Object.678 (http://192.168.0.83/static/js/app.dce78f5dc437c6417355.js:8105:103)
    at n (http://192.168.0.83/static/js/manifest.bba22ef4cc111880865d.js:9:18)
    at window.webpackJsonp (http://192.168.0.83/static/js/manifest.bba22ef4cc111880865d.js:16:47)
    at http://192.168.0.83/static/js/app.dce78f5dc437c6417355.js:1:1
undefined
  http://192.168.0.83/static/js/vendor.0d7983918b9901905427.js:74178:58
  http://192.168.0.83/static/js/vendor.0d7983918b9901905427.js:74184:5
  n at http://192.168.0.83/static/js/manifest.bba22ef4cc111880865d.js:8:17
  678 at http://192.168.0.83/static/js/app.dce78f5dc437c6417355.js:8104:102
  n at http://192.168.0.83/static/js/manifest.bba22ef4cc111880865d.js:8:17
  window.webpackJsonp at http://192.168.0.83/static/js/manifest.bba22ef4cc111880865d.js:15:46
  http://192.168.0.83/static/js/app.dce78f5dc437c6417355.js:0:0

**Comment by hcg2008** [comment]
"Uncaught Error: only one instance of babel-polyfill is allowed" caused the problem.

Google Chrome[19904:5241419] *** Owner supplied to -[NSTrackingArea initWithRect:options:owner:userInfo:] referenced a deallocating object. 
it seemly has not affect to detction.

**Comment by hcg2008** [comment]
In the code, only import "babel-polyfill" once.
But it can run normally after comment the import.
@jvilk
