### ISSUE TITLE
Unable to get interceptor to detect the initial GET of the application's start page

### ISSUE THREAD

**Issue by buddyp450** [plasma-umass/BLeak#39]
I ran bleak with `proxy-session` in an attempt to debug why my check was timing out and I discovered that if I attempted to get my element in the proxy-session it throws this error.

For:
```
document.getElementById('map-1');
```

I get:

```
Error: Object reference chain is too long
    at protocolError (C:\Users\cpatton\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\chrome-debugging-client\dist\lib\create-debugging-protocol-client.js:122:17)
    at DebuggingProtocol.<anonymous> (C:\Users\cpatton\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\chrome-debugging-client\dist\lib\create-debugging-protocol-client.js:89:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\cpatton\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\chrome-debugging-client\dist\lib\create-debugging-protocol-client.js:4:58)
    at <anonymous>
```

What was interesting to me about this is I have no problem executing the `getElementById` in the chrome devtools console in the window that bleak opens up.

I know this isn't necessarily an issue with the BLeak module but any thoughts?

**Comment by buddyp450** [comment]
So to update my original issue, I'm not sure that this is actually the cause of me not being able to run BLeak... (will update title when appropriate)

I added an extra line to the async _run in the CheckOperation to where my loop now looks like this:
```
while (!this._cancelled) {
  const success = await opSt.chromeDriver.runCode(`typeof(BLeakConfig) !== "undefined" && BLeakConfig.${this._stepType}[${this._id}].check()`);

  // extra debug line to determine if BLeakConfig is ever injected <?>
  const extraDebug = await opSt.chromeDriver.runCode(`typeof(BLeakConfig) !== "undefined"`);

    if (success) {
      // the success condition is never reached because BLeakConfig never exists on the page
      console.log('successfully ran code');
        return;
    }

    console.log('was not successful, waitin 100ms..');
    console.log('extra debug was:', JSON.stringify(extraDebug)); // always false

    await util_1.wait(100);
}
```

So my new understanding is that BLeakConfig is actually never globally being injected into the page? Is that correct? Curious as to why this would happen. I'll be digging more into the BLeak source today and hopefully will come up with an answer but if anyone has any ideas as to why this would be happening they would be much appreciated!

**Comment by jvilk** [comment]
The proxy [should be injecting BleakConfig in a <script> tag into the HTML document](https://github.com/plasma-umass/BLeak/blob/master/src/lib/mitmproxy_interceptor.ts#L52). If you don't see this in the source of the webpage, then it's not injecting BleakConfig.

One reason that it might not be injecting BleakConfig is that the HTML's MIME type isn't `text/html`:
https://github.com/plasma-umass/BLeak/blob/master/src/lib/mitmproxy_interceptor.ts#L137

I'd check if it's injected into the HTML document first. If not, check the document's MIME type.

**Comment by buddyp450** [comment]
@jvilk thanks for your reply, I was able to determine my server was indeed not returning the correct MimeType - however - after correcting that, it still seems to not be working.

I inspected the proxy and chrome driver further and noticed it's not actually proxy'ing the initial page load. The interceptor is connecting well afterwards which I'm thinking is the problem. Will update when I have more information.

**Comment by buddyp450** [comment]
I un-commented one of the debug lines that I found in the typescript source the further proves the point:
```
[200] https://www.gstatic.com/chrome/intelligence/assist/ranker/models/translate/2017/03/translate_ranker_model_20170329.pb.bin: text/html
[200] https://c.tile.openstreetmap.org/3/1/4.png: image/png
[200] https://b.tile.openstreetmap.org/3/0/4.png: image/png
[200] https://b.tile.openstreetmap.org/3/3/4.png: image/png
...
```

**Comment by jvilk** [comment]
Hmm, redirects should work. Are you using a service worker or something else that might cache stuff without hitting the network?

**Comment by jvilk** [comment]
Closing due to inactivity.
