### ISSUE TITLE
ssl_client_socket_impl.cc(947)] handshake failed

### ISSUE THREAD

**Issue by perqa** [plasma-umass/BLeak#46]
Running
`bleak run --config BLeak-config.js --out build/`
results in
`DevTools listening on ws://127.0.0.1:59781/devtools/browser/b8feca57-07a9-440f-a0ba-daa9cccd6f2d
[=                   ] 2% [2/72] 2.1s (ETA 71.9s) Navigating to http://localhost/abcctv/src/[34747:17923:0612/111554.232051:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -100
[34747:17923:0612/111554.277968:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -100
[34747:17923:0612/111554.305943:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -100
[34747:17923:0612/111604.398984:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -100
[34747:17923:0612/111604.406970:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -100
[34747:17923:0612/111604.474942:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -100
[34747:17923:0612/111623.805647:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -100
[34747:17923:0612/111625.392422:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -100
[34747:17923:0612/111627.909682:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -100
Unable to transform /complete/search - going to proceed with untransformed JavaScript!
Error:
{ SyntaxError: unknown: Unexpected token (1:0)
> 1 | )]}'
    | ^
  2 | ["",[],[],[],{"google:clientdata":{"bpc":false,"tlw":false},"google:suggesttype":[],"google:verbatimrelevance":851}]
    at Parser.pp$5.raise (/Users/username/.nvm/versions/node/v10.15.3/lib/node_modules/bleak-detector/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/username/.nvm/versions/node/v10.15.3/lib/node_modules/bleak-detector/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/Users/username/.nvm/versions/node/v10.15.3/lib/node_modules/bleak-detector/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/Users/username/.nvm/versions/node/v10.15.3/lib/node_modules/bleak-detector/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/username/.nvm/versions/node/v10.15.3/lib/node_modules/bleak-detector/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/username/.nvm/versions/node/v10.15.3/lib/node_modules/bleak-detector/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/username/.nvm/versions/node/v10.15.3/lib/node_modules/bleak-detector/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/username/.nvm/versions/node/v10.15.3/lib/node_modules/bleak-detector/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExpression (/Users/username/.nvm/versions/node/v10.15.3/lib/node_modules/bleak-detector/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseStatement (/Users/username/.nvm/versions/node/v10.15.3/lib/node_modules/bleak-detector/node_modules/babylon/lib/index.js:1906:19)
  pos: 0,
  loc: Position { line: 1, column: 0 },
  _babel: true,
  codeFrame:
   '\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 | \u001b[39m)]}\u001b[32m\'\u001b[39m\n \u001b[90m   | \u001b[39m\u001b[31m\u001b[1m^\u001b[22m\u001b[39m\n \u001b[90m 2 | \u001b[39m[\u001b[32m""\u001b[39m\u001b[33m,\u001b[39m[]\u001b[33m,\u001b[39m[]\u001b[33m,\u001b[39m[]\u001b[33m,\u001b[39m{\u001b[32m"google:clientdata"\u001b[39m\u001b[33m:\u001b[39m{\u001b[32m"bpc"\u001b[39m\u001b[33m:\u001b[39m\u001b[36mfalse\u001b[39m\u001b[33m,\u001b[39m\u001b[32m"tlw"\u001b[39m\u001b[33m:\u001b[39m\u001b[36mfalse\u001b[39m}\u001b[33m,\u001b[39m\u001b[32m"google:suggesttype"\u001b[39m\u001b[33m:\u001b[39m[]\u001b[33m,\u001b[39m\u001b[32m"google:verbatimrelevance"\u001b[39m\u001b[33m:\u001b[39m\u001b[35m851\u001b[39m}]\u001b[0m' }
[34747:17923:0612/111643.392441:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -100
[34747:17923:0612/111646.635631:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -100
[34747:17923:0612/111648.435471:ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -100
Error: Operation timed out.
[=                   ] 4% [3/72] 122.1s (ETA 2808.7s) Waiting for login[0].check() === true[34740:30211:0612/111655.111667:ERROR:browser_process_sub_thread.cc(221)] Waited 77 ms for network service`

The url is correct and accessible in a web browser (Apache server, port 80)

**Comment by perqa** [comment]
This error occurs if you specify 
`exports.url = "http://localhost";`

A simple solution is to create a virtualhost using a fake domain name, like dev.loc, pointing to the same directory as localhost. 

Perhaps this info could be added to the ReadMe, to save others from unnecessary struggle?
