### ISSUE TITLE
Cannot install BLeak via NPM

### ISSUE THREAD

**Issue by william-ferguson-au** [plasma-umass/BLeak#76]
Lots of errors like these:

```
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan_converters_43_inl.h(22): error C2664: 'v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate *) const'
: cannot convert argument 1 from 'v8::Local<v8::Context>' to 'v8::Isolate *' (compiling source file ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\no
de_modules\bufferutil\build\bufferutil.vcxproj]
  c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan_converters_43_inl.h(22): note: No user-defined-conversion operator available that can perform this con
  version, or the operator cannot be called (compiling source file ..\src\bufferutil.cc)
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan_converters_43_inl.h(40): error C2664: 'bool v8::Value::BooleanValue(v8::Isolate *) const': cannot conver
t argument 1 from 'v8::Local<v8::Context>' to 'v8::Isolate *' (compiling source file ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\buff
erutil\build\bufferutil.vcxproj]
  c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan_converters_43_inl.h(40): note: No user-defined-conversion operator available that can perform this con
  version, or the operator cannot be called (compiling source file ..\src\bufferutil.cc)
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan_implementation_12_inl.h(103): error C2664: 'v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8:
:Context>,v8::FunctionCallback,v8::Local<v8::Value>,int,v8::ConstructorBehavior,v8::SideEffectType)': cannot convert argument 1 from 'v8::Isolate *' to 'v8::Local<v8::Context>' (compiling so
urce file ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
  c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan_implementation_12_inl.h(105): note: No constructor could take the source type, or constructor overload
   resolution was ambiguous (compiling source file ..\src\bufferutil.cc)
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan_implementation_12_inl.h(337): error C2660: 'v8::StringObject::New': function does not take 1 arguments (
compiling source file ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
  c:\users\william\appdata\local\node-gyp\cache\14.16.1\include\node\v8.h(5854): note: see declaration of 'v8::StringObject::New' (compiling source file ..\src\bufferutil.cc)
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan_implementation_12_inl.h(337): error C2059: syntax error: ')' (compiling source file ..\src\bufferutil.cc
) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1034): error C2660: 'v8::Value::ToString': function does not take 0 arguments (compiling source file .
.\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
  c:\users\william\appdata\local\node-gyp\cache\14.16.1\include\node\v8.h(2810): note: see declaration of 'v8::Value::ToString' (compiling source file ..\src\bufferutil.cc)
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1044): error C2664: 'int v8::String::WriteUtf8(v8::Isolate *,char *,int,int *,int) const': cannot conv
ert argument 1 from 'char *' to 'v8::Isolate *' (compiling source file ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\b
ufferutil.vcxproj]
  c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1044): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or f
  unction-style cast (compiling source file ..\src\bufferutil.cc)
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1818): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments (compiling source file
 ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1824): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments (compiling source file
 ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1830): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments (compiling source file
 ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1836): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments (compiling source file
 ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1835): error C2672: 'Nan::EscapableHandleScope::Escape': no matching overloaded function found (compil
ing source file ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1842): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments (compiling source file
 ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1842): error C2672: 'Nan::EscapableHandleScope::Escape': no matching overloaded function found (compil
ing source file ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1847): error C2661: 'v8::Object::Get': no overloaded function takes 1 arguments (compiling source file
 ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1847): error C2672: 'Nan::EscapableHandleScope::Escape': no matching overloaded function found (compil
ing source file ..\src\bufferutil.cc) [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan_object_wrap.h(24): error C2039: 'IsNearDeath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCop
yablePersistentTraits<T>>' [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
  c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1859): note: see declaration of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan_object_wrap.h(67): error C2039: 'MarkIndependent': is not a member of 'Nan::Persistent<v8::Object,v8::No
nCopyablePersistentTraits<T>>' [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
  c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1859): note: see declaration of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan_object_wrap.h(124): error C2039: 'IsNearDeath': is not a member of 'Nan::Persistent<v8::Object,v8::NonCo
pyablePersistentTraits<T>>' [C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
  c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\nan\nan.h(1859): note: see declaration of 'Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>'
          with
          [
              T=v8::Object
          ] (compiling source file ..\src\bufferutil.cc)
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\src\bufferutil.cc(12): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [C:\U
sers\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
  c:\users\william\appdata\local\node-gyp\cache\14.16.1\include\node\v8.h(2869): note: see declaration of 'v8::Value::Int32Value' (compiling source file ..\src\bufferutil.cc)
c:\users\william\appdata\roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\src\bufferutil.cc(13): error C2660: 'v8::Value::Int32Value': function does not take 0 arguments [C:\U
sers\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil\build\bufferutil.vcxproj]
  c:\users\william\appdata\local\node-gyp\cache\14.16.1\include\node\v8.h(2869): note: see declaration of 'v8::Value::Int32Value' (compiling source file ..\src\bufferutil.cc)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\William\AppData\Roaming\npm\node_modules\bleak-detector\node_modules\bufferutil
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

```

**Comment by william-ferguson-au** [comment]
Upgraded Node from  v15 to v17 and Bleak installs but mitmproxy==4.0.1 fails to install.
```
Installing collected packages: cryptography, wsproto, urwid, tornado, sortedcontainers, ruamel.yaml, pyperclip, pyparsing, pyOpenSSL, pydivert, passlib, ldap3, kaitaistruct, h2, click, certifi, brotlipy, blinker, mitmproxy
    Running setup.py install for cryptography ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\William\\AppData\\Local\\Temp\\pip-install-81g3q86j\\cryptography_a67fea70b36645279ec6b44c420ba3f6\\setup.py'"'"'; __file__='"'"'C:\\Users\\William\\AppData\\Local\\Temp\\pip-install-81g3q86j\\cryptography_a67fea70b36645279ec6b44c420ba3f6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\William\AppData\Local\Temp\pip-record-r2hkthma\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python310\Include\cryptography'
         cwd: C:\Users\William\AppData\Local\Temp\pip-install-81g3q86j\cryptography_a67fea70b36645279ec6b44c420ba3f6\
    Complete output (113 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\cryptography
    copying src\cryptography\exceptions.py -> build\lib.win-amd64-3.10\cryptography
    copying src\cryptography\fernet.py -> build\lib.win-amd64-3.10\cryptography
    copying src\cryptography\utils.py -> build\lib.win-amd64-3.10\cryptography
    copying src\cryptography\__about__.py -> build\lib.win-amd64-3.10\cryptography
    copying src\cryptography\__init__.py -> build\lib.win-amd64-3.10\cryptography
    creating build\lib.win-amd64-3.10\cryptography\hazmat
    copying src\cryptography\hazmat\__init__.py -> build\lib.win-amd64-3.10\cryptography\hazmat
    creating build\lib.win-amd64-3.10\cryptography\x509
    copying src\cryptography\x509\base.py -> build\lib.win-amd64-3.10\cryptography\x509
    copying src\cryptography\x509\certificate_transparency.py -> build\lib.win-amd64-3.10\cryptography\x509
    copying src\cryptography\x509\extensions.py -> build\lib.win-amd64-3.10\cryptography\x509
    copying src\cryptography\x509\general_name.py -> build\lib.win-amd64-3.10\cryptography\x509
    copying src\cryptography\x509\name.py -> build\lib.win-amd64-3.10\cryptography\x509
    copying src\cryptography\x509\oid.py -> build\lib.win-amd64-3.10\cryptography\x509
    copying src\cryptography\x509\__init__.py -> build\lib.win-amd64-3.10\cryptography\x509
    creating build\lib.win-amd64-3.10\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\interfaces.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\__init__.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends
    creating build\lib.win-amd64-3.10\cryptography\hazmat\bindings
    copying src\cryptography\hazmat\bindings\__init__.py -> build\lib.win-amd64-3.10\cryptography\hazmat\bindings
    creating build\lib.win-amd64-3.10\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\cmac.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\constant_time.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\hashes.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\hmac.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\keywrap.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\mac.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\padding.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\serialization.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\__init__.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives
    creating build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\aead.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\backend.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ciphers.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\cmac.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\decode_asn1.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\dh.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\dsa.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ec.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\encode_asn1.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\hashes.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\hmac.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\rsa.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\utils.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\x25519.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\x509.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\__init__.py -> build\lib.win-amd64-3.10\cryptography\hazmat\backends\openssl
    creating build\lib.win-amd64-3.10\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\binding.py -> build\lib.win-amd64-3.10\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\_conditional.py -> build\lib.win-amd64-3.10\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\__init__.py -> build\lib.win-amd64-3.10\cryptography\hazmat\bindings\openssl
    creating build\lib.win-amd64-3.10\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\dh.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\dsa.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\ec.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\padding.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\rsa.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\utils.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\x25519.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\__init__.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\asymmetric
    creating build\lib.win-amd64-3.10\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\aead.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\algorithms.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\base.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\modes.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\__init__.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\ciphers
    creating build\lib.win-amd64-3.10\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\concatkdf.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\hkdf.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\kbkdf.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\pbkdf2.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\scrypt.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\x963kdf.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\__init__.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\kdf
    creating build\lib.win-amd64-3.10\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\hotp.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\totp.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\utils.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\__init__.py -> build\lib.win-amd64-3.10\cryptography\hazmat\primitives\twofactor
    running egg_info
    writing src\cryptography.egg-info\PKG-INFO
    writing dependency_links to src\cryptography.egg-info\dependency_links.txt
    writing requirements to src\cryptography.egg-info\requires.txt
    writing top-level names to src\cryptography.egg-info\top_level.txt
    reading manifest file 'src\cryptography.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs\_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    adding license file 'LICENSE'
    adding license file 'LICENSE.APACHE'
    adding license file 'LICENSE.BSD'
    adding license file 'AUTHORS.rst'
    writing manifest file 'src\cryptography.egg-info\SOURCES.txt'
    running build_ext
    generating cffi module 'build\\temp.win-amd64-3.10\\Release\\_padding.c'
    creating build\temp.win-amd64-3.10
    creating build\temp.win-amd64-3.10\Release
    generating cffi module 'build\\temp.win-amd64-3.10\\Release\\_constant_time.c'
    generating cffi module 'build\\temp.win-amd64-3.10\\Release\\_openssl.c'
    building '_openssl' extension
    creating build\temp.win-amd64-3.10\Release\build
    creating build\temp.win-amd64-3.10\Release\build\temp.win-amd64-3.10
    creating build\temp.win-amd64-3.10\Release\build\temp.win-amd64-3.10\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Python310\include -IC:\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcbuild\temp.win-amd64-3.10\Release\_openssl.c /Fobuild\temp.win-amd64-3.10\Release\build\temp.win-amd64-3.10\Release\_openssl.obj
    _openssl.c
    build\temp.win-amd64-3.10\Release\_openssl.c(570): fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\William\\AppData\\Local\\Temp\\pip-install-81g3q86j\\cryptography_a67fea70b36645279ec6b44c420ba3f6\\setup.py'"'"'; __file__='"'"'C:\\Users\\William\\AppData\\Local\\Temp\\pip-install-81g3q86j\\cryptography_a67fea70b36645279ec6b44c420ba3f6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\William\AppData\Local\Temp\pip-record-r2hkthma\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python310\Include\cryptography' Check the logs for full command output.

```

**Comment by william-ferguson-au** [comment]
I gave up trying to install mitmproxy==4.0.1 and instead just installed latest mitmproxy (7.0.4) which wortked.
Hopefully that will be OK for BLeak.

**Comment by william-ferguson-au** [comment]
Well, I could install mitmproxy-7.0.4 but when I run bleak I get:
```
C:\Source\wylas\bleak-detector>bleak run --config bleak-config-recorder.js --out bleak_output
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: connect ECONNREFUSED ::1:50538
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 50538
}

Node.js v17.1.0
```

Any ideas?

**Comment by rmr949** [comment]
I am facing the same issue. It would be great if anyone can provide any workarounds here. Thanks!
