### ISSUE TITLE
Unable to find browser for type ${browserType}

### ISSUE THREAD

**Issue by foreseaz** [plasma-umass/BLeak#82]
Hi BLeak devs, when I run `bleak run --config ./config.js --out ./`, it outputs error:

```
/Users/chenxizh/.node/lib/node_modules/bleak-detector/node_modules/chrome-debugging-client/dist/lib/resolve-browser.js:38
        throw new Error(`Unable to find browser for type ${browserType}`);
              ^

Error: Unable to find browser for type system
    at findExecutablePath (/Users/chenxizh/.node/lib/node_modules/bleak-detector/node_modules/chrome-debugging-client/dist/lib/resolve-browser.js:38:15)
    at Object.resolveBrowser [as default] (/Users/chenxizh/.node/lib/node_modules/bleak-detector/node_modules/chrome-debugging-client/dist/lib/resolve-browser.js:21:26)
    at Session.<anonymous> (/Users/chenxizh/.node/lib/node_modules/bleak-detector/node_modules/chrome-debugging-client/dist/lib/create-session.js:44:61)
    at Generator.next (<anonymous>)
    at /Users/chenxizh/.node/lib/node_modules/bleak-detector/node_modules/chrome-debugging-client/dist/lib/create-session.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/chenxizh/.node/lib/node_modules/bleak-detector/node_modules/chrome-debugging-client/dist/lib/create-session.js:3:12)
    at Session.spawnBrowser (/Users/chenxizh/.node/lib/node_modules/bleak-detector/node_modules/chrome-debugging-client/dist/lib/create-session.js:43:16)
    at spawnChromeBrowser (/Users/chenxizh/.node/lib/node_modules/bleak-detector/dist/node/lib/chrome_driver.js:55:28)
    at Function.Launch (/Users/chenxizh/.node/lib/node_modules/bleak-detector/dist/node/lib/chrome_driver.js:132:35)
```

I believe it's caused by https://github.com/TracerBench/chrome-debugging-client, and BLeak is using the version `v0.6.2` released at 2018. Now the V1 and V2 of `chrome-debugging-client` API is complete different, may I know if BLeak devs can resolve this issue by support newer version of `chrome-debugging-client`?

**Comment by foreseaz** [comment]
Currently, the only hacky fix is downloading the 2018 version of Chrome.

Refer to here https://github.com/nleak/chrome-debugging-client-test-local

**Comment by kevinkleine** [comment]
That links to here: https://google-chrome.en.uptodown.com/mac/download/1766474, a page where chrome version 69 can be downloaded for MacOS.
Does anyone know how to install Chrome v69 on Linux? 

(It would be helpful to mention this in the readme btw)

**Comment by emeryberger** [comment]
We would welcome pull requests for documentation as well as support for more recent versions of the chrome-debugging-client.
